// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrations need Neon's direct (non-pooled) connection; the app itself
  // talks to the pooled DATABASE_URL through the PrismaNeon adapter — see
  // src/infrastructure/db/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
